pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
                git branch: 'main', 
                    credentialsId: 'github-credentials', 
                    url: 'git@github.com:authcornelius/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running pytest...'
                sh '''
                    source venv/bin/activate
                    pytest messaging_app/tests --maxfail=1 --disable-warnings -q --junitxml=report.xml
                '''
            }
        }

        stage('Publish Test Report') {
            steps {
                echo 'Publishing test results...'
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}
