pipeline {
    agent any

    environment {
        PYTHON = '/usr/bin/python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/yourusername/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/tests/ --junitxml=report.xml'
            }
        }

        stage('Archive Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
